<!DOCTYPE html>

<html>

<head>

<meta charset="utf-8" />
<meta name="generator" content="pandoc" />
<meta http-equiv="X-UA-Compatible" content="IE=EDGE" />




<title>Beer and Breweries Case Study</title>

<script src="site_libs/jquery-1.11.3/jquery.min.js"></script>
<meta name="viewport" content="width=device-width, initial-scale=1" />
<link href="site_libs/bootstrap-3.3.5/css/bootstrap.min.css" rel="stylesheet" />
<script src="site_libs/bootstrap-3.3.5/js/bootstrap.min.js"></script>
<script src="site_libs/bootstrap-3.3.5/shim/html5shiv.min.js"></script>
<script src="site_libs/bootstrap-3.3.5/shim/respond.min.js"></script>
<script src="site_libs/navigation-1.1/tabsets.js"></script>
<link href="site_libs/highlightjs-9.12.0/default.css" rel="stylesheet" />
<script src="site_libs/highlightjs-9.12.0/highlight.js"></script>

<style type="text/css">code{white-space: pre;}</style>
<style type="text/css">
  pre:not([class]) {
    background-color: white;
  }
</style>
<script type="text/javascript">
if (window.hljs) {
  hljs.configure({languages: []});
  hljs.initHighlightingOnLoad();
  if (document.readyState && document.readyState === "complete") {
    window.setTimeout(function() { hljs.initHighlighting(); }, 0);
  }
}
</script>



<style type="text/css">
h1 {
  font-size: 34px;
}
h1.title {
  font-size: 38px;
}
h2 {
  font-size: 30px;
}
h3 {
  font-size: 24px;
}
h4 {
  font-size: 18px;
}
h5 {
  font-size: 16px;
}
h6 {
  font-size: 12px;
}
.table th:not([align]) {
  text-align: left;
}
</style>




<style type = "text/css">
.main-container {
  max-width: 940px;
  margin-left: auto;
  margin-right: auto;
}
code {
  color: inherit;
  background-color: rgba(0, 0, 0, 0.04);
}
img {
  max-width:100%;
}
.tabbed-pane {
  padding-top: 12px;
}
.html-widget {
  margin-bottom: 20px;
}
button.code-folding-btn:focus {
  outline: none;
}
summary {
  display: list-item;
}
</style>


<style type="text/css">
/* padding for bootstrap navbar */
body {
  padding-top: 51px;
  padding-bottom: 40px;
}
/* offset scroll position for anchor links (for fixed navbar)  */
.section h1 {
  padding-top: 56px;
  margin-top: -56px;
}
.section h2 {
  padding-top: 56px;
  margin-top: -56px;
}
.section h3 {
  padding-top: 56px;
  margin-top: -56px;
}
.section h4 {
  padding-top: 56px;
  margin-top: -56px;
}
.section h5 {
  padding-top: 56px;
  margin-top: -56px;
}
.section h6 {
  padding-top: 56px;
  margin-top: -56px;
}
.dropdown-submenu {
  position: relative;
}
.dropdown-submenu>.dropdown-menu {
  top: 0;
  left: 100%;
  margin-top: -6px;
  margin-left: -1px;
  border-radius: 0 6px 6px 6px;
}
.dropdown-submenu:hover>.dropdown-menu {
  display: block;
}
.dropdown-submenu>a:after {
  display: block;
  content: " ";
  float: right;
  width: 0;
  height: 0;
  border-color: transparent;
  border-style: solid;
  border-width: 5px 0 5px 5px;
  border-left-color: #cccccc;
  margin-top: 5px;
  margin-right: -10px;
}
.dropdown-submenu:hover>a:after {
  border-left-color: #ffffff;
}
.dropdown-submenu.pull-left {
  float: none;
}
.dropdown-submenu.pull-left>.dropdown-menu {
  left: -100%;
  margin-left: 10px;
  border-radius: 6px 0 6px 6px;
}
</style>

<script>
// manage active state of menu based on current page
$(document).ready(function () {
  // active menu anchor
  href = window.location.pathname
  href = href.substr(href.lastIndexOf('/') + 1)
  if (href === "")
    href = "index.html";
  var menuAnchor = $('a[href="' + href + '"]');

  // mark it active
  menuAnchor.parent().addClass('active');

  // if it's got a parent navbar menu mark it active as well
  menuAnchor.closest('li.dropdown').addClass('active');
});
</script>

<!-- tabsets -->

<style type="text/css">
.tabset-dropdown > .nav-tabs {
  display: inline-table;
  max-height: 500px;
  min-height: 44px;
  overflow-y: auto;
  background: white;
  border: 1px solid #ddd;
  border-radius: 4px;
}

.tabset-dropdown > .nav-tabs > li.active:before {
  content: "";
  font-family: 'Glyphicons Halflings';
  display: inline-block;
  padding: 10px;
  border-right: 1px solid #ddd;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open > li.active:before {
  content: "&#xe258;";
  border: none;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open:before {
  content: "";
  font-family: 'Glyphicons Halflings';
  display: inline-block;
  padding: 10px;
  border-right: 1px solid #ddd;
}

.tabset-dropdown > .nav-tabs > li.active {
  display: block;
}

.tabset-dropdown > .nav-tabs > li > a,
.tabset-dropdown > .nav-tabs > li > a:focus,
.tabset-dropdown > .nav-tabs > li > a:hover {
  border: none;
  display: inline-block;
  border-radius: 4px;
  background-color: transparent;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open > li {
  display: block;
  float: none;
}

.tabset-dropdown > .nav-tabs > li {
  display: none;
}
</style>

<!-- code folding -->




</head>

<body>


<div class="container-fluid main-container">




<div class="navbar navbar-default  navbar-fixed-top" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="index.html">Apurv's Data Science Projects</a>
    </div>
    <div id="navbar" class="navbar-collapse collapse">
      <ul class="nav navbar-nav">
        <li>
  <a href="index.html">About Me</a>
</li>
<li>
  <a href="Apurv_DS_Project_1.html">Beer Case Study</a>
</li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        
      </ul>
    </div><!--/.nav-collapse -->
  </div><!--/.container -->
</div><!--/.navbar -->

<div class="fluid-row" id="header">



<h1 class="title toc-ignore">Beer and Breweries Case Study</h1>
<h4 class="date">10/5/2020</h4>

</div>


<div id="load-libraries" class="section level1">
<h1>Load Libraries</h1>
<pre><code>## Loading required package: NLP</code></pre>
<pre><code>## 
## Attaching package: &#39;dplyr&#39;</code></pre>
<pre><code>## The following objects are masked from &#39;package:plyr&#39;:
## 
##     arrange, count, desc, failwith, id, mutate, rename, summarise, summarize</code></pre>
<pre><code>## The following objects are masked from &#39;package:stats&#39;:
## 
##     filter, lag</code></pre>
<pre><code>## The following objects are masked from &#39;package:base&#39;:
## 
##     intersect, setdiff, setequal, union</code></pre>
<pre><code>## ── Attaching packages ───────────────────────────────────────────────────────────────────── tidyverse 1.3.0 ──</code></pre>
<pre><code>## ✓ ggplot2 3.3.2     ✓ purrr   0.3.4
## ✓ tibble  3.0.3     ✓ stringr 1.4.0
## ✓ readr   1.3.1     ✓ forcats 0.5.0</code></pre>
<pre><code>## ── Conflicts ──────────────────────────────────────────────────────────────────────── tidyverse_conflicts() ──
## x ggplot2::annotate() masks NLP::annotate()
## x dplyr::arrange()    masks plyr::arrange()
## x purrr::compact()    masks plyr::compact()
## x dplyr::count()      masks plyr::count()
## x dplyr::failwith()   masks plyr::failwith()
## x dplyr::filter()     masks stats::filter()
## x dplyr::id()         masks plyr::id()
## x dplyr::lag()        masks stats::lag()
## x dplyr::mutate()     masks plyr::mutate()
## x dplyr::rename()     masks plyr::rename()
## x dplyr::summarise()  masks plyr::summarise()
## x dplyr::summarize()  masks plyr::summarize()</code></pre>
<pre><code>## Loading required package: lattice</code></pre>
<pre><code>## 
## Attaching package: &#39;caret&#39;</code></pre>
<pre><code>## The following object is masked from &#39;package:purrr&#39;:
## 
##     lift</code></pre>
<pre><code>## data.table 1.13.0 using 1 threads (see ?getDTthreads).  Latest news: r-datatable.com</code></pre>
<pre><code>## **********
## This installation of data.table has not detected OpenMP support. It should still work but in single-threaded mode.
## This is a Mac. Please read https://mac.r-project.org/openmp/. Please engage with Apple and ask them for support. Check r-datatable.com for updates, and our Mac instructions here: https://github.com/Rdatatable/data.table/wiki/Installation. After several years of many reports of installation problems on Mac, it&#39;s time to gingerly point out that there have been no similar problems on Windows or Linux.
## **********</code></pre>
<pre><code>## 
## Attaching package: &#39;data.table&#39;</code></pre>
<pre><code>## The following object is masked from &#39;package:purrr&#39;:
## 
##     transpose</code></pre>
<pre><code>## The following objects are masked from &#39;package:dplyr&#39;:
## 
##     between, first, last</code></pre>
<pre><code>## No renderer backend detected. gganimate will default to writing frames to separate files
## Consider installing:
## - the `gifski` package for gif output
## - the `av` package for video output
## and restarting the R session</code></pre>
<pre><code>## Registered S3 method overwritten by &#39;GGally&#39;:
##   method from   
##   +.gg   ggplot2</code></pre>
<pre><code>## Loading required package: ggthemes</code></pre>
</div>
<div id="introduction" class="section level1">
<h1>Introduction</h1>
<p>We have evaluated the data of the Breweries across USA and various different popular Beers with their Alcohol content (ABV) and Bitterness level (IBU). We did a thorough analysis of the data provided and came up with some interesting facts. We also have some recommendations following our data analysis provided towards the end of the presentation.</p>
<p>We analyzed the number of breweries across US. The distribution of breweries varies significantly across the country. Colorado and California are the states with most Breweries. While Delaware and West Virginia are among the states with lowest number of breweries.</p>
<p>Below Bar chart and Heat-map gives a good pictorial representation of the data.</p>
<p><img src="Apurv_DS_Project_1_files/figure-html/unnamed-chunk-3-1.png" width="672" /></p>
<p>Below is the Heat-map with same data with different visualization.</p>
<p><img src="Apurv_DS_Project_1_files/figure-html/unnamed-chunk-4-1.png" width="672" /></p>
<p>Heat-map helps to easily identify which states are the ones with the most breweries. The two states with the most breweries are California and Colorado, with 39 and 47 breweries respectively.</p>
<p>Now, we will merge the two data sets. Snippet of merged data is provided below. This merge results in a data-frame of 2410 rows.</p>
<pre><code>## [1] 2410</code></pre>
<pre><code>##   Brew_ID            Brewery        City State     Beer.Name Beer_ID   ABV IBU
## 1       1 NorthGate Brewing  Minneapolis    MN       Pumpion    2689 0.060  38
## 2       1 NorthGate Brewing  Minneapolis    MN    Stronghold    2688 0.060  25
## 3       1 NorthGate Brewing  Minneapolis    MN   Parapet ESB    2687 0.056  47
## 4       1 NorthGate Brewing  Minneapolis    MN  Get Together    2692 0.045  50
## 5       1 NorthGate Brewing  Minneapolis    MN Maggie&#39;s Leap    2691 0.049  26
## 6       1 NorthGate Brewing  Minneapolis    MN    Wall&#39;s End    2690 0.048  19
##                                 Style Ounces
## 1                         Pumpkin Ale     16
## 2                     American Porter     16
## 3 Extra Special / Strong Bitter (ESB)     16
## 4                        American IPA     16
## 5                  Milk / Sweet Stout     16
## 6                   English Brown Ale     16</code></pre>
<pre><code>##      Brew_ID                       Brewery          City State                 Beer.Name Beer_ID   ABV IBU
## 2405     556         Ukiah Brewing Company         Ukiah    CA             Pilsner Ukiah      98 0.055  NA
## 2406     557       Butternuts Beer and Ale Garrattsville    NY         Porkslap Pale Ale      49 0.043  NA
## 2407     557       Butternuts Beer and Ale Garrattsville    NY           Snapperhead IPA      51 0.068  NA
## 2408     557       Butternuts Beer and Ale Garrattsville    NY         Moo Thunder Stout      50 0.049  NA
## 2409     557       Butternuts Beer and Ale Garrattsville    NY  Heinnieweisse Weissebier      52 0.049  NA
## 2410     558 Sleeping Lady Brewing Company     Anchorage    AK Urban Wilderness Pale Ale      30 0.049  NA
##                        Style Ounces
## 2405         German Pilsener     12
## 2406 American Pale Ale (APA)     12
## 2407            American IPA     12
## 2408      Milk / Sweet Stout     12
## 2409              Hefeweizen     12
## 2410        English Pale Ale     12</code></pre>
<p>With the merged data, we first needs to check-out if there are any missing values. After data evaluation, we identified that there are only two variables with missing data. ABV is missing 62 values while IBU is missing 1005 rows.Since its a large number of missing values we need to identify a way to impute the missing values.</p>
<pre><code>## `summarise()` regrouping output by &#39;key&#39; (override with `.groups` argument)</code></pre>
<p><img src="Apurv_DS_Project_1_files/figure-html/unnamed-chunk-6-1.png" width="672" /></p>
<p>Next we plot IBU and ABV distribution.</p>
<pre><code>## `stat_bin()` using `bins = 30`. Pick better value with `binwidth`.</code></pre>
<pre><code>## Warning: Removed 62 rows containing non-finite values (stat_bin).</code></pre>
<p><img src="Apurv_DS_Project_1_files/figure-html/unnamed-chunk-7-1.png" width="672" /></p>
<pre><code>## `stat_bin()` using `bins = 30`. Pick better value with `binwidth`.</code></pre>
<pre><code>## Warning: Removed 1005 rows containing non-finite values (stat_bin).</code></pre>
<p><img src="Apurv_DS_Project_1_files/figure-html/unnamed-chunk-7-2.png" width="672" /></p>
<p>Quick visual inspection into the distribution of each variable, we notice that IBU is highly right skewed while ABV is slightly skewed.</p>
<p>Each type of beer style has its unique bitterness which might vary a bit from brand to brand but will still be in same ballpark for the beer style. There are 100 beer styles and more than 1,000 missing values we felt that the best approach was not to impute the missing IBU with the median IBU from all the known data for IBU, instead we decided to impute the missing values with medians for ABV, while for IBU we calculated the median for each beer style and imputed missing data with the median IBU value for that style.</p>
<p>There were also 5 beers with a missing style. We decided to drop those records.</p>
<p>Next, we computed the median Alcohol content (ABV) and median Bitterness (IBU) fir each state.</p>
<p>Median IBU by state:</p>
<p><img src="Apurv_DS_Project_1_files/figure-html/unnamed-chunk-9-1.png" width="672" /></p>
<p>Median ABV by State:</p>
<p><img src="Apurv_DS_Project_1_files/figure-html/unnamed-chunk-10-1.png" width="672" /></p>
<p>Delaware and West Virginia are by far leading on the IBU and New Hampshire among the lowest.</p>
<p>In terms of alcohol content West Virginia is leading again which gives an impression there could be a relationship between the IBU and ABV.</p>
<p>Next we identified the states with a Beer with highest Alcohol content (ABV) and Beer with most bitterness.</p>
<pre><code>##              Style Brew_ID                 Brewery    City State
## 1 Quadrupel  Quad       52 Upslope Brewing Company Boulder    CO
##                                              Beer.Name Beer_ID   ABV Ounces imputed_IBU
## 1 Lee Hill Series Vol. 5 - Belgian Style Quadrupel Ale    2565 0.128   19.2          24</code></pre>
<p>The state with the maximum ABV in a beer is CO. The beer is the Lee Hill Series Vol. 5 - Belgian Style Quadruple Ale with an ABV of 0.128.</p>
<pre><code>##                            Style Brew_ID                 Brewery    City State                 Beer.Name
## 1 American Double   Imperial IPA     375 Astoria Brewing Company Astoria    OR Bitter Bitch Imperial IPA
##   Beer_ID   ABV Ounces imputed_IBU
## 1     980 0.082     12         138</code></pre>
<p>The state with the maximum IBU in a beer is OR. The beer is the Bitter Bitch Imperial IPA with an IBU of 138.</p>
<p>Next, we calculated the mean, max and median of ABV across the states. Also, checked the distribution,</p>
<pre><code>##    Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
## 0.00100 0.05000 0.05600 0.05968 0.06700 0.12800</code></pre>
<pre><code>## `stat_bin()` using `bins = 30`. Pick better value with `binwidth`.</code></pre>
<p><img src="Apurv_DS_Project_1_files/figure-html/unnamed-chunk-13-1.png" width="672" /><img src="Apurv_DS_Project_1_files/figure-html/unnamed-chunk-13-2.png" width="672" /></p>
<p>It appears that the distribution of the ABV variable is slightly right skewed. There appears to be outliers particularly on the left side as ABV is almost zero.<br />
Min: 0.10% , Median: 5.60% , Mean: 5.96% , Max: 12.80%</p>
<pre><code>## `geom_smooth()` using formula &#39;y ~ x&#39;</code></pre>
<p><img src="Apurv_DS_Project_1_files/figure-html/unnamed-chunk-14-1.png" width="672" /></p>
<pre><code>## [1] 0.5802225</code></pre>
<pre><code>## 
## Call:
## lm(formula = ABV ~ imputed_IBU, data = impute_data)
## 
## Residuals:
##       Min        1Q    Median        3Q       Max 
## -0.056510 -0.006384 -0.002144  0.004060  0.073830 
## 
## Coefficients:
##              Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept) 4.627e-02  4.438e-04  104.25   &lt;2e-16 ***
## imputed_IBU 3.291e-04  9.423e-06   34.92   &lt;2e-16 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 0.01091 on 2403 degrees of freedom
## Multiple R-squared:  0.3367, Adjusted R-squared:  0.3364 
## F-statistic:  1220 on 1 and 2403 DF,  p-value: &lt; 2.2e-16</code></pre>
<p>From looking at the scatter-plot above it seems that there is a positive linear relation between ABV and IBU variables. As the ABV the increases the IBU is expected to increase as well. Correlation coefficient of 58.02% explains the variability in IBU based on the changes in ABV. This suggest some evidence that the more alcohol content in the beer the bitter it will be which can be associated to the fact that more bitterness requires breweries to add sweetness to the beer to balance the taste and additional sugar leads to higher alcohol. Which makes it apparent that increase in IBU leads to increase in ABV and vice versa.</p>
<p>To assess the relation between IBU and ABV between IPA and Ales we will first need to create a variable with classifies the beers between “Ale”, “IPA”, and “other”. We will then filter out the “other” variable from the data set. This will result in a data set containing only “ALE” and “IPA” labels.</p>
<p><img src="Apurv_DS_Project_1_files/figure-html/unnamed-chunk-16-1.png" width="672" /></p>
<p>We ran 50 iterations of the K-NN (K nearest neighbors) classier to choose the K with the highest accuracy classifying between “ALE” and “IPA”. It appears that the best value K with highest accuracy is 5. We will use K = 5 to run different train/test splits.</p>
<p>The Accuracy, specificity and sensitivity measures are quite high for K=5. Accuracy is at 90%.Specificity and Sensitivity at 87.0% and 92.0% respectively.</p>
<pre><code>## [1] 0.9048203</code></pre>
<pre><code>## [1] 0.8699283</code></pre>
<pre><code>## [1] 0.9247805</code></pre>
<p><img src="Apurv_DS_Project_1_files/figure-html/unnamed-chunk-18-1.png" width="672" /></p>
<p>From the above plots its evident that ABV and IBU are correlated and varies significantly for IPA and ALEs. We can see a clear trend that the higher value of IBU is associated to IPAs while smaller values of IBU associated to ALEs. There is middle ground where IPAs and ALEs both overlap for the same level of IBUs and ABV but that area is comparatively small. There is a clear distinction between ALE and IPAs based on the IBU and ABV values.</p>
<p>Since, we know that IPAs and ALEs are clearly different and have different properties. We took our analysis to the next step. We checked the most popular words among the Beer Styles and among Beer Names.</p>
<pre><code>## Loading required package: RColorBrewer</code></pre>
<pre><code>## Warning in tm_map.SimpleCorpus(., removeNumbers): transformation drops documents</code></pre>
<pre><code>## Warning in tm_map.SimpleCorpus(., removePunctuation): transformation drops documents</code></pre>
<pre><code>## Warning in tm_map.SimpleCorpus(., stripWhitespace): transformation drops documents</code></pre>
<pre><code>## Warning in tm_map.SimpleCorpus(docs, content_transformer(tolower)): transformation drops documents</code></pre>
<pre><code>## Warning in tm_map.SimpleCorpus(docs, removeWords, stopwords(&quot;english&quot;)): transformation drops documents</code></pre>
<pre><code>## Warning in tm_map.SimpleCorpus(., removeNumbers): transformation drops documents</code></pre>
<pre><code>## Warning in tm_map.SimpleCorpus(., removePunctuation): transformation drops documents</code></pre>
<pre><code>## Warning in tm_map.SimpleCorpus(., stripWhitespace): transformation drops documents</code></pre>
<pre><code>## Warning in tm_map.SimpleCorpus(docs, content_transformer(tolower)): transformation drops documents</code></pre>
<pre><code>## Warning in tm_map.SimpleCorpus(docs, removeWords, stopwords(&quot;english&quot;)): transformation drops documents</code></pre>
<p>Word Cloud - Beer Styles</p>
<p><img src="Apurv_DS_Project_1_files/figure-html/unnamed-chunk-20-1.png" width="672" /></p>
<p>Word Cloud - Beer Names</p>
<p><img src="Apurv_DS_Project_1_files/figure-html/unnamed-chunk-21-1.png" width="672" /></p>
<p>We notice the most popular words are American, IPA and ALE.</p>
<p>Now we will run another test to check if the IPA and ALE have different Mean for IBUs and ABV.</p>
<pre><code>## 
##  Welch Two Sample t-test
## 
## data:  ale_ipa$imputed_IBU by ale_ipa$ipa_ale
## t = -42.582, df = 1095.1, p-value &lt; 2.2e-16
## alternative hypothesis: true difference in means is not equal to 0
## 95 percent confidence interval:
##  -39.37772 -35.90862
## sample estimates:
## mean in group ale mean in group ipa 
##          33.72304          71.36620</code></pre>
<pre><code>## 
##  Welch Two Sample t-test
## 
## data:  ale_ipa$ABV by ale_ipa$ipa_ale
## t = -19.143, df = 1070.2, p-value &lt; 2.2e-16
## alternative hypothesis: true difference in means is not equal to 0
## 95 percent confidence interval:
##  -0.01317336 -0.01072383
## sample estimates:
## mean in group ale mean in group ipa 
##        0.05659782        0.06854641</code></pre>
<p>Two sample t-test confirms that the mean of IBU and ABV is different for ALE from IPA. This confirms our earlier inference from the KNN test.</p>
<p>Powered with this information, we tried to focus on the top 5 states in the US in terms of consumption of beer.</p>
<p>The top 5 states in terms of beer consumption are California, Texas, Florida, New York and Pennsylvania. referring to the report published at <a href="https://vinepair.com/articles/map-states-drink-beer-america-2020/" class="uri">https://vinepair.com/articles/map-states-drink-beer-america-2020/</a></p>
<p><img src="Apurv_DS_Project_1_files/figure-html/unnamed-chunk-23-1.png" width="672" /></p>
<p>Based on the US census report. Texas is adding more population every year than any other state in the USA. <a href="https://www.census.gov/newsroom/press-releases/2019/popest-nation.html" class="uri">https://www.census.gov/newsroom/press-releases/2019/popest-nation.html</a></p>
<p>In terms of Beer consumption Texas is at number 2 (as mentioned above). Considering the growth in population and the beer consumption in Texas. We recommend to launch new beer(s) in the state of Texas.</p>
<p>Considering there is a huge demand for IPA and Texas has lot less IPAs compared to ALEs as shown the plot above. Since American, IPAs are most popular beer styles, we recommend American Pale Ale (APA) or Indian Pale Ale(IPA) for Texas market.</p>
</div>




</div>

<script>

// add bootstrap table styles to pandoc tables
function bootstrapStylePandocTables() {
  $('tr.header').parent('thead').parent('table').addClass('table table-condensed');
}
$(document).ready(function () {
  bootstrapStylePandocTables();
});


</script>

<!-- tabsets -->

<script>
$(document).ready(function () {
  window.buildTabsets("TOC");
});

$(document).ready(function () {
  $('.tabset-dropdown > .nav-tabs > li').click(function () {
    $(this).parent().toggleClass('nav-tabs-open')
  });
});
</script>

<!-- code folding -->


<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    script.src  = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML";
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>

</body>
</html>
